apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  namespace: rik8s
  labels:
     app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        # IMPORTANT: Replace with your actual image from a container registry
        image: crashrik/gateway-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: USER_SERVICE_URL
          value: "http://user-service:3000" # Using Kubernetes internal DNS
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3001" # Using Kubernetes internal DNS
        - name: ORDER_SERVICE_URL
          value: "http://order-service:3002" # Using Kubernetes internal DNS
        - name: NODE_ENV
          value: "development"
        startupProbe:
          httpGet:
            path: /health
            port: 3003
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"