apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: rik8s
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: crashrik/order-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "development"
        startupProbe:
          httpGet: 
            path: /health
            port: 3002 
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet: 
            path: /health
            port: 3002 
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet: 
            path: /health
            port: 3002 
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"