apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  namespace: rik8s
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: crashrik/product-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "development"
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"