apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: rik8s
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: crashrik/user-service:v1 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 6 # 6 * 10s = 60s, matching start_period
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"