apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: rik8s
spec:
  selector:
    app: gateway-service
  ports:
  - protocol: TCP
    port: 80         # The port your Ingress will forward to
    targetPort: 3003 # The port on the gateway container