apiVersion: v1
kind: Service
metadata:
  name: user-service # This name is used for service discovery (DNS)
  namespace: rik8s
spec:
  type: ClusterIP # Internal service, not exposed outside the cluster
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 3000       # Port other services will use to connect
    targetPort: 3000 # Port on the container
